### ISSUE TITLE
ApiKeys label has to be unique among all ApiKeys of a User

### ISSUE THREAD

**Issue by KerstenBreuer** [ghga-de/datameta#118]
The above needs to be enforced.

**Comment by lkuchenb** [comment]
Does this still apply with the current ID based handling?

**Comment by KerstenBreuer** [comment]
No technically, you can give duplicated labels. I guess this is the responsibility of the user

**Comment by KerstenBreuer** [comment]
Can be closed?

**Comment by lkuchenb** [comment]
Yup
