### ISSUE TITLE
Change License to Apache 2

### ISSUE THREAD

**Issue by KerstenBreuer** [ghga-de/datameta#180]
It might be better to replace the copyright notices (in every [file](https://github.com/ghga-de/datameta/blob/main/datameta/api/apikeys.py#L1-L21)) by a general and standard license for the entire repo.

I am a big fan of Apache 2.0 (= MIT + protection against patent trolling).

@lkuchenb, @KorayKirli what do you think?

**Comment by KerstenBreuer** [comment]
Just to add, most technology transfer agencies only accept standard licenses. It would be a great overhead for them to study and understand custom licenses. Apache 2.0 allows use in both open-source and closed-source/for-profit project, thus it can boost the adoption of open-source works like datameta

**Comment by KorayKirli** [comment]
Makes sense, EGA also uses that
https://github.com/EGA-archive/ega-data-api

**Comment by lkuchenb** [comment]
I'm not sure what you mean, you don't think MIT is standard? I mean it's the most used open source license after all, even before the GPL 😅 . Yes, it's ancient and doesn't consider patents, I don't think that people are afraid to be patent trolled by a University though. That being said, I'm open to switch from MIT to Apache though if we feel that has an advantage 👍

**Comment by lkuchenb** [comment]
Fixed in #215
