### ISSUE TITLE
Front end always shows demo mode

### ISSUE THREAD

**Issue by lkuchenb** [ghga-de/datameta#232]

**Comment by cschu** [comment]
I thought that was intentional :/

**Comment by lkuchenb** [comment]
@cschu It's actually a feature of  DataMeta that you can switch it into demo mode and it will discard all uploaded files after processing but treat them in the database as if they existed. Just the indicator in the footer seems broken, i.e. always on 😅

**Comment by MoritzHahn1337** [comment]
```
request.registry.settings.get(['datameta.demo_mode'])
'false'
```

I'm guessing, it does not parse the string, but justs returns true.
