### ISSUE TITLE
ZIPCode and PCRCt columns are not optional 

### ISSUE THREAD

**Issue by erskck1** [ghga-de/datameta#283]
In the documentation, ZIPCode and PCR Ct values seem optional, but the samplesheet cannot pass the validation without giving them.

**Comment by lkuchenb** [comment]
Thanks for reporting this, there is a known issue with empty values in submitted sample sheets which was fixed in #277 but not yet deployed to the test system. The latest version will be deployed shortly.

The issue should not occur when you submit data via the API or Python client.

**Comment by lkuchenb** [comment]
This issue should be resolved since the last deployment. Please don't hesitate to reopen this in case you are still running into the same problem.
