### ISSUE TITLE
Implement Account Management

### ISSUE THREAD

**Issue by lkuchenb** [ghga-de/datameta#32]

**Comment by KerstenBreuer** [comment]
This will include:  
- registration by the user with:
  - username
  - desired password
  - Full Name
  - Organization affiliation
  - work e-mail
  - desired group to be part of
- users will receive mail to confirm
- Admins will receive mail to approve
- Further Admin options:
  - delete Account
  - inactivate Account
- Further User Options:
  - reset password (confirmation via mail required)

@lkuchenb do you agree?

**Comment by KerstenBreuer** [comment]
One other question might be whether users are allowed to be part of multiple groups?

For initial feel is that restriction to one group might be enough for 90% of use cases.

**Comment by lkuchenb** [comment]
Yes, I'd go for that right now and that's also what the database schema can handle right now (gid being a property of the user entity) 👍

**Comment by lkuchenb** [comment]
This issue is partly fixed and partly solved. Parts are still tracked under #153 and #154.
