### ISSUE TITLE
`site_read` allows access to foreign unsubmitted files

### ISSUE THREAD

**Issue by lkuchenb** [ghga-de/datameta#354]
https://github.com/ghga-de/datameta/blob/5bf318fdadd0655031430a9a14b2b283cf2c1d30/datameta/security/authz.py#L24-L31

Staged, yet unsubmitted files should always be private to the user

**Comment by cschu** [comment]
just files or also metadatasets?

**Comment by lkuchenb** [comment]
Shouldn't be possible for both

**Comment by lkuchenb** [comment]
@cschu Can this be closed?

**Comment by cschu** [comment]
That seems to have been fixed.
