### ISSUE TITLE
Add metadataset attributes for replacement logic

### ISSUE THREAD

**Issue by lkuchenb** [ghga-de/datameta#361]
The replacement logic of metadatasets will require the following additional attributes in the database model:

* `metadatasets.replaced_by : [FK metadatasets.id]`
* `metadatasets.deprecated_label : str`
* `metadatasets.is_deprecated : bool`

**Comment by cschu** [comment]
@lkuchenb should these changes already cascade to the `metadatasetresponses` etc.?

**Comment by lkuchenb** [comment]
> @lkuchenb should these changes already cascade to the `metadatasetresponses` etc.?

This issue was meant to track only the addition of the database attributes. In the end these attributes also need to be added to the schemas that reflect a metadataset.

**Comment by lkuchenb** [comment]
Fixed in #384
