### ISSUE TITLE
Create administrative API endpoint to delete user's OTP token

### ISSUE THREAD

**Issue by lkuchenb** [ghga-de/datameta#481]
Add an endpoint `DELETE:/totp-secret/{user_id}` that enables site admins to delete a user's TOTP secret. This is required to recover from a situation where the user has lost access to the TOTP secret.

**Comment by cschu** [comment]
@lkuchenb should this be `DELETE` or `POST`? The secret is stored as a field of `User`, not in a separate table and would be set to `NULL/None`. I have implemented it as `DELETE` for now.
