### ISSUE TITLE
Newer versions of `qrcode` don't support `make_path`

### ISSUE THREAD

**Issue by ckaipf** [ghga-de/datameta#504]
https://github.com/ghga-de/datameta/blob/edb0d6e0e371720d0f9dfff1ace198560b4ee016/datameta/security/tfaz.py#L96-L105

Newer versions of qrcode don't support method `make_path` anymore (AttributeError: `SvgPathFillImage` object has no attribute `make_path`).
PR #503 hotfixes this, however would be good to update our code here.
@cschu do you remember how you implemented this? Thanks!

**Comment by lkuchenb** [comment]
https://github.com/ghga-de/datameta/blob/edb0d6e0e371720d0f9dfff1ace198560b4ee016/datameta/templates/settfa.pt#L84-L86

This seems to be the relevant bit, only the path is injected here. `qr_code.to_string()` would get you the entire SVG for later injection, but would require setting things like size already before hand (`box_size` arg I guess).

**Comment by cschu** [comment]
Looking into it. The path is now hidden away somewhere. 🤮

**Comment by ckaipf** [comment]
I think it's okay, we thought about using the to_string() method, I tried it already, should work

**Comment by cschu** [comment]
lovely that I never get those messages in time ><
