### ISSUE TITLE
Wide View Option

### ISSUE THREAD

**Issue by lkuchenb** [ghga-de/datameta#53]
Add a toggle to the interface that enables a "wide view" that removes the `max-width` attribute from the main div. Especially when sample sheets have a lot of columns users will want to make use of screen space.

**Comment by lkuchenb** [comment]
Should switch the main container class from `container` to `container-fluid`: https://getbootstrap.com/docs/5.0/layout/containers/

**Comment by MoritzHahn1337** [comment]
Button is active & Works. Added some padding around the container as well.
Button says "Wide Screen View" in normal mode, "Normal View" in Widescreen mode. Was the best, I could come up to

Open Questions:
-> Should we change the style and/or the text of the button? 
Maybe replace with an Icon?

-> Where on the page should we put it?
Currently in footer, but it might be desireable to scroll the footer away...

-> Currently it is available on every page (located on layout.pt). Should we keep it there, or only keep it for the submit page?

-> Should the footer do widescreen on toggle as well? Should it even be widescreen all the time?

**Comment by lkuchenb** [comment]
It would be best if you would open a PR on this so that one can comment on the code and discuss the open questions there!
